### ISSUE TITLE
Result::unwrap()` on an Err value: Os code 18

### ISSUE THREAD

**Issue by DmitruMoth** [etra0/taskmgr-video#1]
Cannot inject dll to taskmgr, i also tried xenos for inject, but it still doesn't work.
Log: 

```
injector.exe Taskmgr.exe dll.dll
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 18, kind: Other, message: "There are no more files." }', injector\src\main.rs:84:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

os info: windows 10 ltsc 1809 64 bit

**Comment by etra0** [comment]
You have to put the full path for the dll, like
```
injector.exe Taskmgr.exe "C:\Users\MyUser\Documents\(...)\dll.dll"
```

**Comment by DmitruMoth** [comment]
Same error
```
PS D:\path\to\taskmgr-video> cargo run Taskmgr.exe "D:\path\to\taskmgr-video\target\debug\dll.dll"
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target\debug\injector.exe Taskmgr.exe D:\path\to\taskmgr-video\target\debug\dll.dll`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 18, kind: Other, message: "There are no more files." }', injector\src\main.rs:84:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\injector.exe Taskmgr.exe D:\path\to\taskmgr-video\target\debug\dll.dll` (exit code: 101)
```

**Comment by etra0** [comment]
Is your taskmgr already open when executing the injection? if not, open that first then run the injection!

**Comment by DmitruMoth** [comment]
Taskmgr close if i inject with the same error, i think problem is in dll, xenos also cannot inject

**Comment by etra0** [comment]
there's two reasons I can think of:
1. When you open the task manager, don't go to the performance tab until the injection is made
2. Your windows build have different offsets

If it's the latter, I have no plans on increasing support since it is just a experiment.
